#Importing Numpy library

In [43]:
import numpy as np

In [44]:
arr1 = np.array([1, 2, 3, 4, 5])

In [45]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [46]:
arr1

array([1, 2, 3, 4, 5])

In [47]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr1.shape

(5,)

In [49]:
arr1.dtype

dtype('int64')

In [50]:
arr1.ndim

1

In [51]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [54]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [56]:
arr1[0]

np.int64(1)

In [57]:
arr1[-1]

np.int64(5)

In [58]:
arr2[0]

array([1, 2, 3])

In [59]:
arr1[1:4]

array([2, 3, 4])

In [60]:
arr2[:, 1]

array([2, 5])

In [61]:
a2 = np.array([9,8,7,6])
a3 = np.array([3,4,5,8])

In [62]:
a2 + 5

array([14, 13, 12, 11])

In [63]:
a2 * 2

array([18, 16, 14, 12])

In [64]:
a3 ** 2

array([ 9, 16, 25, 64])

In [65]:
a2 + a3

array([12, 12, 12, 14])

In [66]:
# Array Methods
np.mean(arr1)

np.float64(3.0)

In [67]:
np.sum(arr1)

np.int64(15)

In [68]:
np.max(arr1)

np.int64(5)

In [69]:
np.min(arr1)

np.int64(1)

In [70]:
np.std(arr1)

np.float64(1.4142135623730951)

In [71]:
hours = np.array([2,4,6,3,7,5,1,8])

In [72]:
average = np.mean(hours)
print("Average study hours:", average)

Average study hours: 4.5


In [73]:
max_hours = np.max(hours)
min_hours = np.min(hours)
print("Max study hours:", max_hours)
print("Min study hours:", min_hours)

Max study hours: 8
Min study hours: 1


In [74]:
high_performers = hours[hours > 5]
print("Students who studied more than 5 hours:", high_performers)
print("Count:", len(high_performers))

Students who studied more than 5 hours: [6 7 8]
Count: 3


In [75]:
doubled_hours = hours * 2
print("Doubled study hours:", doubled_hours)

Doubled study hours: [ 4  8 12  6 14 10  2 16]
