In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.shape

(5,)

In [10]:
arr1.dtype

dtype('int64')

In [11]:
arr1.ndim

1

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.arrange(0,10,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
arr1[0]

np.int64(1)

In [20]:
arr1[-1]

np.int64(5)

In [21]:
arr1[1:4]

array([2, 3, 4])

In [22]:
arr2[0]

array([1, 2, 3])

In [23]:
arr2[:, 1]

array([2, 5])

In [24]:
arr1 + 5

array([ 6,  7,  8,  9, 10])

In [25]:
arr1 * 2

array([ 2,  4,  6,  8, 10])

In [26]:
arr1 ** 2

array([ 1,  4,  9, 16, 25])

In [27]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

In [28]:
np.mean(arr1)

np.float64(3.0)

In [29]:
np.sum(arr1)

np.int64(15)

In [30]:
np.max(arr1)

np.int64(5)

In [31]:
np.min(arr1)

np.int64(1)

In [32]:
np.std(arr1)

np.float64(1.4142135623730951)

In [33]:
hours = np.array([2,4,6,3,7,5,1,8])